# Generated by Django 2.2.6 on 2019-10-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='released',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='runtime',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
