# Generated by Django 2.2.6 on 2019-10-27 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies_api', '0002_auto_20191026_0841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='add_date',
            new_name='add_datetime',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='mod_date',
            new_name='mod_datetime',
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='comment',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='movies_api.Movie'),
        ),
    ]
