# Generated by Django 2.2.6 on 2019-10-27 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_api', '0004_comment_add_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='add_date',
            field=models.DateField(default=datetime.date(2019, 10, 27)),
        ),
    ]
