# Generated by Django 2.2.6 on 2019-10-27 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_api', '0008_auto_20191027_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='add_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
