# Generated by Django 2.2.6 on 2019-10-27 18:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies_api', '0003_auto_20191027_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='add_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
