# Generated by Django 2.2.6 on 2019-10-27 18:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies_api', '0007_auto_20191027_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='add_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
